#!/usr/bin/env bash

# install vundle
echo "Installing Vundle"
mkdir -p ~/.vim/bundle
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

# get vimrc
echo "Getting .vimrc"
curl -L https://raw.github.com/bengl/dotfiles/master/vimrc > ~/.vimrc

# install vundle bundles
echo "Installing vundle bundles"
vim +BundleInstall +qall

echo ""
echo ""
echo "Now install this font https://gist.github.com/raw/1595572/417a3fa36e35ca91d6d23ac961071094c26e5fad/Menlo-Powerline.otf"
